[UPDATES]
tabarra/PlumeESX-recipe pull request #3
Opened 2021-04-19 20:55 UTC by Mycroft-Studios

updates Identity, Vehicleshop and Jobs. Adds pma-voice

2021-04-26 00:01 UTC, tabarra commented on recipe.yaml
> -    src: https://github.com/esx-framework/es_extended
Nope, need to stick to the main esx, what changed compared to yours?

2021-04-26 06:34 UTC, Mycroft-Studios commented on recipe.yaml
> -    src: https://github.com/esx-framework/es_extended
Ah, that was for debugging and forgot to change it back

2021-04-26 12:41 UTC, Mycroft-Studios commented on recipe.yaml
> -    src: https://github.com/esx-framework/es_extended
Fixed

2021-04-26 19:04 UTC, RockySouthpaw commented on recipe.yaml
> +    dest: ./resources/esx_property
Shouldnt this be 
`./resources/[esx]/esx_property`

2021-05-07 14:24 UTC, tabarra requested changes
Absolutely no for the ref changes to master... this 100% defeats the prupose of a ref, and breaks things all the time (for instance the crap you did to the legacy branch)

2021-05-13 09:41 UTC, tabarra commented
This PR kinda fell out of control and got abandoned.

2021-05-13 09:41 UTC, closed without merging