Feat: Update plume esx to esx legacy
tabarra/PlumeESX-recipe pull request #8
Opened 2021-07-03 17:58 UTC by Hamy-os

As the repositories plume depends on were moved into one this pr updates the links. Enjoy ;)

2021-07-03 20:01 UTC, Scottywonderful commented
This section of the receipe.yaml requires to be updated as per #9 

```
   # Download ESX resources
   - action: download_github
     src: https://github.com/esx-framework/es_extended
     ref: 694cd6757802c432bd025f8251dee33760080eff
     dest: ./resources/[esx]/es_extended
```

2021-07-03 20:09 UTC, Hamy-os commented
> This section of the receipe.yaml requires to be updated as per #9
> 
> ```
>    # Download ESX resources
>    - action: download_github
>      src: https://github.com/esx-framework/es_extended
>      ref: 694cd6757802c432bd025f8251dee33760080eff
>      dest: ./resources/[esx]/es_extended
> ```

this isnt needed as its all included in the esx legacy repo

2021-07-03 20:11 UTC, Scottywonderful commented
> > This section of the receipe.yaml requires to be updated as per #9
> > ```
> >    # Download ESX resources
> >    - action: download_github
> >      src: https://github.com/esx-framework/es_extended
> >      ref: 694cd6757802c432bd025f8251dee33760080eff
> >      dest: ./resources/[esx]/es_extended
> > ```
> 
> this isnt needed as its all included in the esx legacy repo

Yeah, after posting this, I notice you removed it in the request and updating it to the [https://github.com/esx-framework/esx-legacy](https://github.com/esx-framework/esx-legacy) which I believe is a great idea being it has been mostly used recently.

2021-07-03 20:30 UTC, Scottywonderful commented on server.cfg
> +ensure
This extra ensure is not required.
```suggestion
ensure 
```
Lines 74, 87 and 97 is not needed either, it just becomes a huge gap, like this:

`ensure esx_realestateagentjob
ensure



ensure EasyAdmin
`

I suggest it being shortened to this:
`ensure esx_realestateagentjob
ensure EasyAdmin
`

2021-07-03 20:34 UTC, Scottywonderful commented on server.cfg
> +ensure
Hope this helps with this mate :)

2021-07-05 12:32 UTC, thelindat commented
The Legacy repo has *everything*, some of which wouldn't be recommended such as
- esx_voice
- esx_phone
- esx_whitelist

Some resources need their config modified as well such as enabling identiy/society integration, or enabling multicharacter in the ESX config.

2021-08-18 21:21 UTC, tabarra requested changes
change requests :)

2021-08-18 21:21 UTC, tabarra commented on server.cfg
> +ensure [fivem]
there is also a resource called "fivem",  name the folder [cfx-default]

2021-08-18 21:21 UTC, tabarra commented on server.cfg
> +# resource cleanup
starting just to stop it? i don't like this

2021-08-18 21:21 UTC, tabarra commented on todo.md
> +# Welcome to the plumeESX Legacy todo list :P
You can put this on the readme, maybe this encourage people to help.

2021-08-18 21:21 UTC, tabarra commented on recipe.yaml
> +author: Tabarra, Hamy & Chip
you can take chip away

2021-08-18 21:21 UTC, tabarra commented on recipe.yaml
> +    dest: ./resources/[fivem]
name it `cfx-default`, and update the ref to `b907aa74e2826e363979332ac21b9ad98cd82aa1`

2021-08-18 21:21 UTC, tabarra commented on recipe.yaml
> +    src: https://github.com/Hamy-os/plumehello
no motd plz :(

2021-08-18 21:21 UTC, tabarra commented on recipe.yaml
> +  - action: move_path
No need, just use subpath on que action above.

2021-08-18 21:21 UTC, tabarra commented on recipe.yaml
> +  - action: ensure_dir
don't need

2021-08-18 21:21 UTC, tabarra commented on recipe.yaml
> +    dest: ./tmp/rp-radio
update reference, Avarian moved to the root path so no need to use the /tmp/

2021-08-18 21:21 UTC, tabarra commented on recipe.yaml
> +    dest: ./resources/rp-radio
solved by the update above, can delete

2021-08-18 21:21 UTC, tabarra commented on recipe.yaml
> +    search: 'USE `es_extended`;'
Why we doing this? isn't the big sql file already doing these queries?
(same for the one above)

2021-08-18 21:21 UTC, tabarra commented on recipe.yaml
> +    file: ./resources/[legacy]/[esx_addons]/esx_multicharacter/server/main.lua
this accepts a file array, so no need to run the action twice

2021-08-18 21:21 UTC, tabarra commented on recipe.yaml
> +    path: ./tmp
being removed twice

2021-08-18 21:39 UTC, Hamy-os commented on loadingscreen/config.js
>      ],
yeah added a radio keybind

2021-08-18 22:01 UTC, Hamy-os commented
alright all changes done

2021-08-19 02:26 UTC, tabarra commented on loadingscreen/config.js
>      ],
Job menu gone?

2021-08-19 02:30 UTC, merged